<Button>
	font_size: 32
	background_normal: ''
	background_color: (0,0,1,1)

<TextInput>
	background_color: (150/255,150/255,150/255,1)	

<Label>
	font_size: 32

<MyLayout>
	BoxLayout:
		orientation: "vertical"
		size: root.width, root.height
		padding:10
		spacing:10

		Label:
			text: "Name"

		TextInput:
			multiline: False

		Label:
			text: "Favorite Pizza"

		TextInput:
			multiline: False

		Button:
			text: "Submit"
		Button:
			text: "Clear"
			background_color: (1,0,0,1)